name: validate

on:
  push:
  pull_request:

jobs:
  restore_and_format:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"
      - name: Restore
        run: dotnet restore .\GSADUs.Revit.BatchExport.sln
      - name: Format check
        run: dotnet format --verify-no-changes
